//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_Modificadores
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int item1 { get; set; }
        public int item2 { get; set; }
        public int item3 { get; set; }
        public int item4 { get; set; }
        public int item5 { get; set; }
        public int item6 { get; set; }
        public int item7 { get; set; }
        public int item8 { get; set; }
        public int item9 { get; set; }
        public int item10 { get; set; }
        public int item11 { get; set; }
        public int item12 { get; set; }
        public int item13 { get; set; }
        public int item14 { get; set; }
        public int item15 { get; set; }
        public int item16 { get; set; }
        public int item17 { get; set; }
        public int item18 { get; set; }
        public bool Opcional { get; set; }
        public int Maximos { get; set; }
        public int Minimo { get; set; }
    }
}
